---
# 国内源
- name: Add GitLab repository
  copy:
    remote_src: false
    src: gitlab-ce.repo
    dest: /etc/yum.repos.d/gitlab-ce.repo
  when: ansible_os_family == 'RedHat'

- name: Check if GitLab configuration file already exsist
  stat: path=/etc/gitlab/gitlab.rb
  register: gitlab_config_file

- name: Check if GitLab is already installed
  stat: path=/usr/bin/gitlab-ctl
  register: gitlab_file

- name: Define the Gitlab package name
  set_fact:
    gitlab_package_name: "{{ gitlab_edition }}{{ gitlab_package_version_separator }}{{ gitlab_version }}"
  when: gitlab_version != ''

- name: Install GitLab
  package:
    name: "{{ gitlab_package_name | default(gitlab_edition) }}"
    state: present
    update_cache: yes
  when: (gitlab_file.stat.exists == false)

# Start and configure GitLab. Sometimes the first run fails, but after that,
# restarts fix problems, so ignore failures on this run.
- name: Reconfigure GitLab (first run)
  command: >
    gitlab-ctl reconfigure
    creates=/var/opt/gitlab/bootstrapped
  failed_when: false

- name: Create GitLab SSL configuration folder
  file:
    path: /etc/gitlab/ssl
    state: directory
    owner: root
    group: root
    mode: 0700
  when: gitlab_create_self_signed_cert

- name: Create self-signed certificate
  command: >
    openssl req -new -nodes -x509 -subj "{{ gitlab_self_signed_cert_subj }}" -days 3650 \
    -keyout {{ gitlab_ssl_certificate_key }} -out {{ gitlab_ssl_certificate }} -extensions v3_ca
    creates={{ gitlab_ssl_certificate }}
  when: gitlab_create_self_signed_cert

- name: Create pem certificate
  command: >
    openssl dhparam -out {{ gitlab_ssl_dhparam }} 2048
    creates={{ gitlab_ssl_dhparam }}
  when: gitlab_create_self_signed_cert

- name: Copy GitLab configuration file
  template:
    src: "{{ gitlab_config_template }}"
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: 0600
  notify: restart gitlab
