---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

# Install GitLab and its dependencies
- name: Install GitLab dependencies
  yum: name={{ item }} state=present
  loop:
    - openssh-server
    - postfix
    - curl
    - openssl
    - tzdata
    - openssh-clients

- name: postfix | Set postfix server
  include_tasks: postfix.yml

- include_tasks: gitlab.yml